name: Flask CI/CD Pipeline with Canary Deployment
on:
  push:
    branches:
      - canary-deployment

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t flask-app:latest .
          docker images

      # Step 3: Run Flask Docker container
      - name: Run Flask Docker Container
        run: |
          docker run -d --name flask_container -p 7001:7000 flask-app:latest

      # Step 4: Install Locust
      - name: Install Locust
        run: pip install locust

      - name: Test Flask API before Load Test
        run: curl -f http://localhost:7001/health || exit 1

      # Step 5: Run Load Tests
      - name: Run Locust Load Tests
        run: |
          locust -f locustfile.py --headless --users 100 --spawn-rate 10 --run-time 1m --host=http://localhost:7001


      # Step 6: Stop Flask Docker Container
      - name: Stop Flask Docker Container
        run: docker stop flask_container

  model-health-check:
    runs-on: ubuntu-latest
    needs: ci  # Run only if CI passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ONNX Runtime
        run: pip install onnxruntime

      - name: Validate ONNX Model
        #run: python scripts/validate_onnx.py
        run: echo "Simulating traffic shift to Canary..."


  canary-deployment:
    runs-on: ubuntu-latest
    needs: model-health-check  # Deploy only if model passes validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build New Canary Image
        run: |
          docker build -t flask-app:canary .
          docker images

      - name: Deploy New Canary Version
        run: |
          docker run -d --name canary_flask -p 7002:7000 flask-app:canary

      - name: Run Canary Tests
        run: |
          curl -f http://localhost:7002/health || exit 1  # Check health
          locust -f locustfile.py --headless --users 50 --spawn-rate 5 --host=http://localhost:7002

      - name: Gradual Traffic Shift
        run: |
          echo "Simulating traffic shift to Canary..."
          sleep 10
          echo "Canary is stable, rolling out fully!"

      - name: Cleanup
        run: docker stop canary_flask
