name: Flask CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Build Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t flask-app:latest .  # Ensure the image is tagged as flask-app:latest

  # Step 2: Run Flask App and Run Locust Load Tests
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure tests only run after the build step

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Flask Docker Container
        run: |
          docker run -d -p 7001:7000 flask-app:latest  # Use the locally built flask-app:latest image

      - name: Install Locust
        run: pip install locust

      - name: Run Locust Load Tests
        run: |
          locust -f locustfile.py --headless --users 100 --spawn-rate 10 --host=http://localhost:7001

      - name: Stop Flask Docker Container
        run: |
          docker ps -q --filter "ancestor=flask-app" | xargs docker stop  # Stop the container after tests
