name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Set up Docker buildx

    - name: Build Docker image
      run: |
        docker build -t flask-app .  # Build the image with the tag `flask-app`

    - name: Verify image build
      run: |
        docker images  # Verify if the image is built successfully

