name: Flask CI Pipeline

on:
  push:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t flask-app:latest .  # Build the image and tag it as flask-app:latest
          docker images  # List all Docker images to verify the image was built correctly

      # Step 3: Run Flask Docker container
      - name: Run Flask Docker Container
        run: |
          docker run -d -p 7001:7000 flask-app:latest  # Run the Flask app container on port 7001

      # Step 4: Install Locust
      - name: Install Locust
        run: pip install locust

      # Step 5: Run Locust Load Tests
      - name: Run Locust Load Tests
        run: |
          locust -f locustfile.py --headless --users 100 --spawn-rate 10 --host=http://localhost:7001

      # Step 6: Stop Flask Docker container after testing
      - name: Stop Flask Docker Container
        run: |
          docker ps -q --filter "ancestor=flask-app" | xargs docker stop  # Stop the container after tests
